pipelines:
  azure-publish-snapshot-playground:
    group: My-Pipelines
    label_template: ${COUNT}
    environment_variables:
      TAGNAME: "master"
      RELEASE: "false"
    materials:
      azure-functions:
        git: https://github.com/DiegoMejiaSalazar/demogocd.git
        branch: master
        auto_update: true
    stages:
      - PullRepository:
          clean_workspace: true
          fetch_materials: yes
          keep_artifacts: no
          jobs:
            RepoAsArtifact:
              tasks:
                - script: |
                    echo ${TAGNAME}
              artifacts:
                - build:
                    source: "*.json"
                    destination: repo
      - build:
          fetch_materials: no
          jobs:
            buildAndUnitTest:
              tasks:
                - fetch:
                    stage: PullRepo
                    job: RepoAsArtifact
                    source: repo/
                - script: |
                    cd repo
                    az deployment group create --name blanktemplate --resource-group myResourceGroup --template-file demo.json --parameters parameters.json